<a href="https://colab.research.google.com/github/codm12112/DWM-SIT-PRACTICAL/blob/main/DWM_EXP_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
print('Hello')

#Cell 1
dataset = pd.read_excel('/Employee data.xlsx')

#Cell 2
dataset.isnull().sum()

dataset

x=dataset.iloc[:,3:6].values
x

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = 'NaN', strategy='median')
imputer = SimpleImputer().fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = 'NaN', strategy='most_frequent')
imputer = SimpleImputer().fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)

Hello
[[   15     3 57000]
 [   16     1 40200]
 [   12     1 21450]
 ...
 [   15     1 39150]
 [   12     1 21450]
 [   12     1 29400]]
[[   15     3 57000]
 [   16     1 40200]
 [   12     1 21450]
 ...
 [   15     1 39150]
 [   12     1 21450]
 [   12     1 29400]]
